services:    
    db:
        image: mysql:8.0.20
        # command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_librarify:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony

    php:
        build:
            context: ./php-fpm
        environment:
            XDEBUG_CLIENT_HOST: 172.17.0.1
            # XDEBUG_CLIENT_HOST: host.docker.internal # only use macOS
            XDEBUG_CLIENT_PORT: 9005
            # PHP_IDE_CONFIG: serverName=librarify-php #Only use for PHPSTORM
        volumes:
            - ../:/var/www/librarify
            - ./php-fpm/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini #For linux
            - ./php-fpm/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini #For macOS
        depends_on:
            - db
        networks:
            - symfony

    nginx:
        image: nginx:stable-alpine
        ports:
            - 1000:80
        volumes:
            - ../:/var/www/librarify
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - symfony

volumes:
    db_librarify:

networks:
    symfony:

#sudo chmod -R 777 /path/to/directory Run if permissions are denied
    